### PR TITLE
[FEATURE] Mark heroes who will stay idle and not quest

### PR DESCRIPTION
**Pull request by ikn0wkungfu**
- Added a property to Enable this feature in `DFKBotSettings`. This is the only change there except the formatting that VS did:
`public bool EnableNotQuestingWithoutPreferredQuest { get; set; } = false;`
- The setting is used in `DFKBot` method `GetMinStaminaBotHero` to return 999 min stamina if there is no preferred quest assigned to the hero and `EnableNotQuestingWithoutPreferredQuest` is false or `SuggestedQuest` is null.

### CODE REVIEW

**Comment by weghuz** [comment]
I will test this branch tonight. It looks like there are a ton of whitespace changes, was that intentional? Good work nontheless. Hopefully merging later today.

**Comment by ikn0wkungfu** [comment]
> I will test this branch tonight. It looks like there are a ton of whitespace changes, was that intentional? Good work nontheless. Hopefully merging later today.

The whitespace changes are made by Visual Studio probably when I did Ctrl + K + D
Does the change of whitespace break things?

**Comment by weghuz** [comment]
@ikn0wkungfu it doesn't break things but it's generally good to avoid formatting a whole file to change a few lines when making PRs to bigger codebases. Especially if it doesn't change anything. Taking a look at the PR now.

**Comment by weghuz** [comment]
Accepting the PR, good job on it. Tested and seemed to be working fine.

**Pull request merged**
